homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret HA_HOME_LATITUDE
  longitude: !secret HA_HOME_LONGITUDE
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret HA_HOME_ELEVATION
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_named themes

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Sensors
sensor:
  # Weather prediction
  - platform: yr
  - platform: pollenkoll
    sensors:
      - city: Stockholm
        state: Gräs
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: processor_use

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

recorder: !include recorder.yaml

mqtt:
  broker: !env_var HA_SERVER_MQTT_HOST
  port: !env_var HA_SERVER_MQTT_PORT
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

lovelace:
  mode: yaml
