homeassistant:
  customize_glob:
    sensor.pollen*:
      custom_ui_state_card: state-card-custom-ui
      templates:
        hs_color: "if (state === 'no levels') return [0, 0];
        else if (state === 'low levels') return [50, 70];
        else if (state === 'low-moderate levels') return [40, 70];
        else if (state === 'moderate levels') return [30, 70];
        else if (state === 'moderate-high levels') return [20, 85];
        else if (state === 'high levels') return [10, 65];
        else if (state === 'very high levels') return [0, 85];"

  customize:
    sensor.pollen_gras:
      friendly_name: Grass
      icon: mdi:flower

    sensor.pollen_grabo:
      friendly_name: Mugwort
      icon: mdi:flower

    sensor.pollen_bjork:
      friendly_name: Birch
      icon: mdi:leaf

    sensor.pollen_al:
      friendly_name: Al
      icon: mdi:leaf

    sensor.pollen_hassel:
      friendly_name: Hazel
      icon: mdi:leaf

    sensor.pollen_ek:
      friendly_name: Oak
      icon: mdi:leaf
    
sensor:
  - platform: pollenkoll
    sensors:
      - city: Stockholm
        state: Bjork
      # - city: Stockholm
      #   state: Gråbo
      # - city: Stockholm
      #   state: Gräs
  - platform: template
    sensors:
      pollen_grabo:
        friendly_name: "Pollen: gråbo"
        entity_id: "sensor.pollenkoll_stockholm"
        value_template: >-
          {% if is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'i.h.') -%}
            no levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'L') -%}
            low levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'L-M') -%}
            low-moderate levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'M') -%}
            moderate levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'M-H') -%}
            moderate-high levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'H') -%}
            high levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'H-H+') -%}
            very high levels
          {%- endif %}
      pollen_gras:
        friendly_name: "Pollen: gräs"
        entity_id: "sensor.pollenkoll_stockholm"
        value_template: >-
          {% if is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'i.h.') -%}
            no levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'L') -%}
            low levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'L-M') -%}
            low-moderate levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'M') -%}
            moderate levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'M-H') -%}
            moderate-high levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'H') -%}
            high levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'H-H+') -%}
            very high levels
          {%- endif %}
      pollen_bjork:
        friendly_name: "Pollen: björk"
        entity_id: "sensor.pollenkoll_stockholm"
        value_template: >-
          {% if is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'i.h.') -%}
            no levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'L') -%}
            low levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'L-M') -%}
            low-moderate levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'M') -%}
            moderate levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'M-H') -%}
            moderate-high levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'H') -%}
            high levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'H-H+') -%}
            very high levels
          {%- endif %}
      pollen_al:
        friendly_name: "Pollen: al"
        entity_id: "sensor.pollenkoll_stockholm"
        value_template: >-
          {% if is_state_attr('sensor.pollenkoll_stockholm', 'Al', 'i.h.') -%}
            no levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Al', 'L') -%}
            low levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Al', 'L-M') -%}
            low-moderate levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Al', 'M') -%}
            moderate levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Al', 'M-H') -%}
            moderate-high levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Al', 'H') -%}
            high levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Al', 'H-H+') -%}
            very high levels
          {%- endif %}
      pollen_hassel:
        friendly_name: "Pollen: hassel"
        entity_id: "sensor.pollenkoll_stockholm"
        value_template: >-
          {% if is_state_attr('sensor.pollenkoll_stockholm', 'Hassel', 'i.h.') -%}
            no levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Hassel', 'L') -%}
            low levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Hassel', 'L-M') -%}
            low-moderate levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Hassel', 'M') -%}
            moderate levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Hassel', 'M-H') -%}
            moderate-high levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Hassel', 'H') -%}
            high levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Hassel', 'H-H+') -%}
            very high levels
          {%- endif %}
      pollen_ek:
        friendly_name: "Pollen: ek"
        entity_id: "sensor.pollenkoll_stockholm"
        value_template: >-
          {% if is_state_attr('sensor.pollenkoll_stockholm', 'Ek', 'i.h.') -%}
            no levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Ek', 'L') -%}
            low levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Ek', 'L-M') -%}
            low-moderate levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Ek', 'M') -%}
            moderate levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Ek', 'M-H') -%}
            moderate-high levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Ek', 'H') -%}
            high levels
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Ek', 'H-H+') -%}
            very high levels
          {%- endif %}
      pollen_levels:
        friendly_name: "Pollen levels"
        entity_id: "sensor.pollenkoll_stockholm"
        value_template: >-
          {%- if is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'M') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'M-H') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'H') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Björk', 'H-H+') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'M') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'M-H') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'H') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gräs', 'H-H+') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'M') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'M-H') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'H') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Gråbo', 'H-H+') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Al', 'M') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Al', 'M-H') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Al', 'H') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Al', 'H-H+') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Hassel', 'M') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Hassel', 'M-H') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Hassel', 'H') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Hassel', 'H-H+') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Ek', 'M') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Ek', 'M-H') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Ek', 'H') -%}
            high
          {%- elif is_state_attr('sensor.pollenkoll_stockholm', 'Ek', 'H-H+') -%}
            high
          {%- else %}
            low
          {%- endif %}